### ISSUE TITLE
Implement client authentication

### ISSUE THREAD

**Issue by paulmillar** [m-team-kit/alise#1]
An ALISE instance collects personal data about individuals.  This information should probably be protected so that only authorised clients can access the information.

For example, the ALISE admin might request an application key from ALISE and configure a specific client to use that application key when making requests.  The client could present the application key as a bearer token, using the HTTP `Authorization` header, when making requests to ALISE.

Note that the above example is meant only to illustrate the idea.

**Comment by marcvs** [comment]
Thanks for bringing this up. I was waiting for actual usage before progressing here.

The simplest form of client auth could be to simply pass the access token of the user. If that's valid, I could return all linked IDs.

**Comment by paulmillar** [comment]
Hmm, I'm not sure about using the user AT as the service authentication is robust.

The point here is to identify the service making the request; for example, identify the dCache instance that Vega is running.

It's not guaranteed that an access token identifies the service.

There's actually a *lot* of detail skated over in that statement (`aud` claims, JWTs, etc), but I think it's generally true.

I think having some kind of token as a shared secret between the service and ALISE is the minimum that would be robust.

The "correct" approach would be to implement OAuth2 and use this to authorise access to parts of (possibly all of) the ALISE request path.  However, I think any shared secret should work.

**Comment by marcvs** [comment]
Would it be a good idea, if I add one endpoint for creating an API key?
That endpoint would be authorized by :drum:  an access_token of the _developer_

**Comment by paulmillar** [comment]
I think the simplest solution would be to have a database table with a list of API keys.  Each key is just a base64 encoded random number (with suitable number of bits).

ALISE would provide some out-of-bound way to generate a new API token, add it to the database table and report the token to the admin.  For example, this could be a command-line tool that generates the token, injects it directly into the database table and prints the token on the console.  The assumption here is that anyone who can directly manipulate the database is the admin (and has access to all the information anyway).

When an API request is made (e.g., dCache calling out to ALISE), the client (e.g., dCache) provides the API token in the HTTP `Authorization` header (`Authorization: Bearer TOKEN`).  ALISE would compare this with the tokens in the database table containing all the tokens.  It then rejects the request if there's no match.
