### ISSUE TITLE
Reassess API path for users

### ISSUE THREAD

**Issue by paulmillar** [m-team-kit/alise#2]
There is a path `/api/v1/$TARGET/get_mappings/$SUB_AND_ISS`, where `$TARGET` is the target for account linking (e.g., `vega-kc` for Vega's Keycloak instance) and `$SUB_AND_ISS` is the output from the `tools/sub-iss-encode.sh` script.

`$SUB_AND_ISS` is a string build like `ENCODE{ENCODE{SUB} + '@' + ENCODE{ISS}}`, where `+` is string concatenation and `ENCODE` is URL percent-encoding.

There are a couple of issue with this approach.

Under REST, the URL represents "a thing" being acted on.  The `get_mapping` is a verb, which doesn't follow a REST approach.  (The "get" is implied by using the HTTP GET verb).

Second, it isn't clear how to extend this API to support other queries.

Here's a concrete proposal:

    /api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/user/$ENCODED_SUB

where `$ENCODED_ISS` is `ENCODE{ISS}` above, and `$ENCODED_SUB` is `ENCODE{SUB}` above.

This approach is quite flexible; for example, it could be extended to support group mappings in a natural way; e.g.,

    GET /api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/group/$ENCODED_GROUP

It would also support querying all information about a specific issuer:

    GET /api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS

One might also extend the API to support management functions; for example, the API could support deleting (support for) a specific issuer:

    DELETE  /api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS

The API could also support adding ALISE to accept a new issuer:

    echo $ENCODED_ISS | POST /api/v1/target/$TARGET/mapping/issuer

support for querying the list of available issuers:

    GET  /api/v1/target/$TARGET/mapping/issuer/

... etc...

These are all just examples of how a more REST-like request path might be more flexible.

**Comment by marcvs** [comment]
Sure; When I started I just made something up.
I'll add support for `/api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/user/$ENCODED_SUB`
I'll see, if I can easily add support for `/api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/`
I'm not sure what you meant with `$GROUP`, I understand it as an example for future extension.

**Comment by paulmillar** [comment]
>  I understand it as an example for future extension.

Yeah, exactly.  The `$GROUP`was speculation (on my part) on a possible future use for ALISE.

I think the only thing we "need" to do is add support for `/api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/user/$ENCODED_SUB`.

The rest is more speculation on possible new features "we" (i.e., you ;-) might want to implement in the future.

So, feel free to implement `/api/v1/target/$TARGET/mapping/issuer/$ENCODED_ISS/`. However, please don't feel compelled to do that, in order to close this issue.
