### ISSUE TITLE
Cache-control HTTP response headers

### ISSUE THREAD

**Issue by paulmillar** [m-team-kit/alise#7]
ALISE provides information that describes identity mapping.  Such information is very unlikely to change.  The typical scenario is that the user links their local- and federated identities (as identified by usernames, 'sub' claims, etc) once.  After this, the user's identities (local and federated) will likely never change.  There is, perhaps, the likelihood that new identities are introduced, but that (too) is likely a rare event.

Caching is a widely used tool to reduce latency, reduce load on the server (ALISE) and reduce the impact (on dependent services) of a temporary outage (e.g., restart during an admin intervention).  The information provided by ALISE would seem an ideal candidate to support some form of caching.

[RFC 7234](https://datatracker.ietf.org/doc/html/rfc7234) provides a standard mechanisms that allows a server to indicate whether a response should be cached and for how long.

It would be helpful if ALISE were to use these mechanisms to indicate that information should be cached.

**Comment by marcvs** [comment]
Ok; I'll investigate. Also to see if I can inform the client for how long Alise has been caching the linkage (i.e. that may have happened years ago, and the user is gone at one of the home-OPs

**Comment by marcvs** [comment]
Header would currently be:

```
< cache-control: public
< max-age: 31536000
< x-alise-version: 1.0.5
```

Anything missing from your perspective?
