### ISSUE TITLE
Inconsistent error response format

### ISSUE THREAD

**Issue by paulmillar** [m-team-kit/alise#8]
ALISE responds to errors in an inconsistent fashion; e.g.,

Missing `apikey` query parameter:

```
HTTP/1.1 422 Unprocessable Entity
Server: nginx/1.24.0
Date: Sun, 14 Apr 2024 21:10:05 GMT
Content-Type: application/json
Content-Length: 142
Connection: keep-alive

{"detail":[{"type":"missing","loc":["query","apikey"],"msg":"Field required","input":null,"url":"https://errors.pydantic.dev/2.4/v/missing"}]}
```

An unknown `apikey` query parameter:

```
HTTP/1.1 401 Unauthorized
Server: nginx/1.24.0
Date: Sun, 14 Apr 2024 21:10:56 GMT
Content-Type: application/json
Content-Length: 28
Connection: keep-alive

{"message":"invalid apikey"}
```

Although both response are JSON, they follow different schemas.

It would be helpful if a common error schema was adopted for all problems.

Note that [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807) provides a reasonable, standard way of expressing errors.

**Comment by marcvs** [comment]
Ok; I've improved on that v1.0.5 will have it
