### ISSUE TITLE
Extend REST API to allow client to query a list of supported issuers

### ISSUE THREAD

**Issue by paulmillar** [m-team-kit/alise#9]
It may be helpful if the client could obtain a list of issuers (`iss` claim values) that ALISE accepts.

If a client accepts other OPs then it could avoid querying ALISE about tokens to which ALISE will never provide a mapping.

This additional feature is not urgent.

**Comment by marcvs** [comment]
I've included it in v1.0.5, it was easy to add
It's at ` ${ALISE}/alise/supported_issuers`
